name: 2d-game # you probably want to 'snapcraft register <name>'
base: core20 # the base snap is the execution environment for this snap
version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: A 2D game made with OpenGL # 79 char long summary
description: |
  This is a 2D game I made with OpenGL. Use the arrow keys to move the
  square around the screen. And that's it.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

parts:
  part:
    # See 'snapcraft plugins'
    plugin: dump
    source: releases/0.1-linux
    stage-packages:
      - libstdc++6
      - libx11-6
      - libgcc-s1
    after:
      - desktop-glib-only
  desktop-glib-only:
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: glib-only
    plugin: make
    build-packages:
      - libglib2.0-dev
    stage-packages:
      - libglib2.0-bin
